# Generated by Django 5.2 on 2025-04-26 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True)),
                ('imei', models.CharField(blank=True, max_length=100, null=True)),
                ('mac_address', models.CharField(blank=True, max_length=100, null=True)),
                ('device_type', models.CharField(choices=[('smartphone', 'SmartPhone'), ('tablet', 'Tablet'), ('laptop', 'Laptop'), ('other', 'Other')], max_length=20)),
                ('last_latitude', models.FloatField(blank=True, null=True)),
                ('last_longitude', models.FloatField(blank=True, null=True)),
                ('is_stolen', models.BooleanField(default=False)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('license_plate', models.CharField(max_length=100, unique=True)),
                ('make_model', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('year', models.IntegerField(max_length=10)),
                ('rfid_tag', models.CharField(blank=True, max_length=100, null=True)),
                ('last_latitude', models.FloatField(blank=True, null=True)),
                ('last_longitude', models.FloatField(blank=True, null=True)),
                ('is_stolen', models.BooleanField(default=False)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
